// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: work.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_work_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtToken      string                 `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Code          int32                  `protobuf:"varint,127,opt,name=code,proto3" json:"code,omitempty"`      //status code
	Message       string                 `protobuf:"bytes,128,opt,name=message,proto3" json:"message,omitempty"` //status code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_work_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResp) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

func (x *LoginResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_work_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtToken      string                 `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Code          int32                  `protobuf:"varint,127,opt,name=code,proto3" json:"code,omitempty"`      //status code
	Message       string                 `protobuf:"bytes,128,opt,name=message,proto3" json:"message,omitempty"` //status code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_work_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResp) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

func (x *RegisterResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_work_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime    int64                  `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Author        *User                  `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_work_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{5}
}

func (x *Post) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Post) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Post) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

type CreatePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostReq) Reset() {
	*x = CreatePostReq{}
	mi := &file_work_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostReq) ProtoMessage() {}

func (x *CreatePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostReq.ProtoReflect.Descriptor instead.
func (*CreatePostReq) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePostReq) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type CreatePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Code          int32                  `protobuf:"varint,127,opt,name=code,proto3" json:"code,omitempty"`      //status code
	Message       string                 `protobuf:"bytes,128,opt,name=message,proto3" json:"message,omitempty"` //status code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResp) Reset() {
	*x = CreatePostResp{}
	mi := &file_work_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResp) ProtoMessage() {}

func (x *CreatePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResp.ProtoReflect.Descriptor instead.
func (*CreatePostResp) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{7}
}

func (x *CreatePostResp) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CreatePostResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreatePostResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdatePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	PostId        string                 `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostReq) Reset() {
	*x = UpdatePostReq{}
	mi := &file_work_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostReq) ProtoMessage() {}

func (x *UpdatePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostReq.ProtoReflect.Descriptor instead.
func (*UpdatePostReq) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePostReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePostReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdatePostReq) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type UpdatePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,127,opt,name=code,proto3" json:"code,omitempty"`      //status code
	Message       string                 `protobuf:"bytes,128,opt,name=message,proto3" json:"message,omitempty"` //status code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResp) Reset() {
	*x = UpdatePostResp{}
	mi := &file_work_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResp) ProtoMessage() {}

func (x *UpdatePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResp.ProtoReflect.Descriptor instead.
func (*UpdatePostResp) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePostResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdatePostResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        int32                  `protobuf:"varint,1,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_work_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{10}
}

func (x *Pagination) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	PostId        string                 `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,10,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostReq) Reset() {
	*x = ListPostReq{}
	mi := &file_work_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostReq) ProtoMessage() {}

func (x *ListPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostReq.ProtoReflect.Descriptor instead.
func (*ListPostReq) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{11}
}

func (x *ListPostReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ListPostReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ListPostReq) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *ListPostReq) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListPostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PostList      []*Post                `protobuf:"bytes,2,rep,name=post_list,json=postList,proto3" json:"post_list,omitempty"`
	Code          int32                  `protobuf:"varint,127,opt,name=code,proto3" json:"code,omitempty"`      //status code
	Message       string                 `protobuf:"bytes,128,opt,name=message,proto3" json:"message,omitempty"` //status code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostResp) Reset() {
	*x = ListPostResp{}
	mi := &file_work_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostResp) ProtoMessage() {}

func (x *ListPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostResp.ProtoReflect.Descriptor instead.
func (*ListPostResp) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{12}
}

func (x *ListPostResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPostResp) GetPostList() []*Post {
	if x != nil {
		return x.PostList
	}
	return nil
}

func (x *ListPostResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListPostResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPostDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostDetailReq) Reset() {
	*x = GetPostDetailReq{}
	mi := &file_work_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostDetailReq) ProtoMessage() {}

func (x *GetPostDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostDetailReq.ProtoReflect.Descriptor instead.
func (*GetPostDetailReq) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{13}
}

func (x *GetPostDetailReq) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type GetPostDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Code          int32                  `protobuf:"varint,127,opt,name=code,proto3" json:"code,omitempty"`      //status code
	Message       string                 `protobuf:"bytes,128,opt,name=message,proto3" json:"message,omitempty"` //status code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostDetailResp) Reset() {
	*x = GetPostDetailResp{}
	mi := &file_work_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostDetailResp) ProtoMessage() {}

func (x *GetPostDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostDetailResp.ProtoReflect.Descriptor instead.
func (*GetPostDetailResp) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{14}
}

func (x *GetPostDetailResp) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *GetPostDetailResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPostDetailResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeletePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostReq) Reset() {
	*x = DeletePostReq{}
	mi := &file_work_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostReq) ProtoMessage() {}

func (x *DeletePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostReq.ProtoReflect.Descriptor instead.
func (*DeletePostReq) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{15}
}

func (x *DeletePostReq) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type DeletePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,127,opt,name=code,proto3" json:"code,omitempty"`      //status code
	Message       string                 `protobuf:"bytes,128,opt,name=message,proto3" json:"message,omitempty"` //status code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResp) Reset() {
	*x = DeletePostResp{}
	mi := &file_work_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResp) ProtoMessage() {}

func (x *DeletePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResp.ProtoReflect.Descriptor instead.
func (*DeletePostResp) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{16}
}

func (x *DeletePostResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeletePostResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	PostId        string                 `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CreateTime    int64                  `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Author        *User                  `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_work_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{17}
}

func (x *Comment) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Comment) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Comment) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Comment) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

type CreateCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReq) Reset() {
	*x = CreateCommentReq{}
	mi := &file_work_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReq) ProtoMessage() {}

func (x *CreateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReq.ProtoReflect.Descriptor instead.
func (*CreateCommentReq) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{18}
}

func (x *CreateCommentReq) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type CreateCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Code          int32                  `protobuf:"varint,127,opt,name=code,proto3" json:"code,omitempty"`      //status code
	Message       string                 `protobuf:"bytes,128,opt,name=message,proto3" json:"message,omitempty"` //status code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResp) Reset() {
	*x = CreateCommentResp{}
	mi := &file_work_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResp) ProtoMessage() {}

func (x *CreateCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResp.ProtoReflect.Descriptor instead.
func (*CreateCommentResp) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{19}
}

func (x *CreateCommentResp) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *CreateCommentResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateCommentResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListCommentByPostIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,10,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentByPostIdReq) Reset() {
	*x = ListCommentByPostIdReq{}
	mi := &file_work_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentByPostIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentByPostIdReq) ProtoMessage() {}

func (x *ListCommentByPostIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentByPostIdReq.ProtoReflect.Descriptor instead.
func (*ListCommentByPostIdReq) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{20}
}

func (x *ListCommentByPostIdReq) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *ListCommentByPostIdReq) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListCommentByPostIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	CommentList   []*Comment             `protobuf:"bytes,2,rep,name=comment_list,json=commentList,proto3" json:"comment_list,omitempty"`
	Code          int32                  `protobuf:"varint,127,opt,name=code,proto3" json:"code,omitempty"`      //status code
	Message       string                 `protobuf:"bytes,128,opt,name=message,proto3" json:"message,omitempty"` //status code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentByPostIdResp) Reset() {
	*x = ListCommentByPostIdResp{}
	mi := &file_work_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentByPostIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentByPostIdResp) ProtoMessage() {}

func (x *ListCommentByPostIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_work_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentByPostIdResp.ProtoReflect.Descriptor instead.
func (*ListCommentByPostIdResp) Descriptor() ([]byte, []int) {
	return file_work_proto_rawDescGZIP(), []int{21}
}

func (x *ListCommentByPostIdResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListCommentByPostIdResp) GetCommentList() []*Comment {
	if x != nil {
		return x.CommentList
	}
	return nil
}

func (x *ListCommentByPostIdResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListCommentByPostIdResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_work_proto protoreflect.FileDescriptor

const file_work_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"work.proto\x12\x04work\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"w\n" +
	"\tLoginResp\x12\x1b\n" +
	"\tjwt_token\x18\x01 \x01(\tR\bjwtToken\x12\x1e\n" +
	"\x04user\x18\x02 \x01(\v2\n" +
	".work.UserR\x04user\x12\x12\n" +
	"\x04code\x18\x7f \x01(\x05R\x04code\x12\x19\n" +
	"\amessage\x18\x80\x01 \x01(\tR\amessage\"[\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"z\n" +
	"\fRegisterResp\x12\x1b\n" +
	"\tjwt_token\x18\x01 \x01(\tR\bjwtToken\x12\x1e\n" +
	"\x04user\x18\x02 \x01(\v2\n" +
	".work.UserR\x04user\x12\x12\n" +
	"\x04code\x18\x7f \x01(\x05R\x04code\x12\x19\n" +
	"\amessage\x18\x80\x01 \x01(\tR\amessage\"Q\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\xb5\x01\n" +
	"\x04Post\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x05 \x01(\x03R\n" +
	"updateTime\x12\"\n" +
	"\x06author\x18\x06 \x01(\v2\n" +
	".work.UserR\x06author\"/\n" +
	"\rCreatePostReq\x12\x1e\n" +
	"\x04post\x18\x01 \x01(\v2\n" +
	".work.PostR\x04post\"X\n" +
	"\x0eCreatePostResp\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x12\n" +
	"\x04code\x18\x7f \x01(\x05R\x04code\x12\x19\n" +
	"\amessage\x18\x80\x01 \x01(\tR\amessage\"X\n" +
	"\rUpdatePostReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\tR\x06postId\"?\n" +
	"\x0eUpdatePostResp\x12\x12\n" +
	"\x04code\x18\x7f \x01(\x05R\x04code\x12\x19\n" +
	"\amessage\x18\x80\x01 \x01(\tR\amessage\"B\n" +
	"\n" +
	"Pagination\x12\x17\n" +
	"\apage_no\x18\x01 \x01(\x05R\x06pageNo\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x92\x01\n" +
	"\vListPostReq\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\tR\x06postId\x120\n" +
	"\n" +
	"pagination\x18\n" +
	" \x01(\v2\x10.work.PaginationR\n" +
	"pagination\"|\n" +
	"\fListPostResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12'\n" +
	"\tpost_list\x18\x02 \x03(\v2\n" +
	".work.PostR\bpostList\x12\x12\n" +
	"\x04code\x18\x7f \x01(\x05R\x04code\x12\x19\n" +
	"\amessage\x18\x80\x01 \x01(\tR\amessage\"+\n" +
	"\x10GetPostDetailReq\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"b\n" +
	"\x11GetPostDetailResp\x12\x1e\n" +
	"\x04post\x18\x01 \x01(\v2\n" +
	".work.PostR\x04post\x12\x12\n" +
	"\x04code\x18\x7f \x01(\x05R\x04code\x12\x19\n" +
	"\amessage\x18\x80\x01 \x01(\tR\amessage\"(\n" +
	"\rDeletePostReq\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"?\n" +
	"\x0eDeletePostResp\x12\x12\n" +
	"\x04code\x18\x7f \x01(\x05R\x04code\x12\x19\n" +
	"\amessage\x18\x80\x01 \x01(\tR\amessage\"\xc1\x01\n" +
	"\aComment\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\tR\x06postId\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x05 \x01(\x03R\n" +
	"updateTime\x12\"\n" +
	"\x06author\x18\x06 \x01(\v2\n" +
	".work.UserR\x06author\";\n" +
	"\x10CreateCommentReq\x12'\n" +
	"\acomment\x18\x01 \x01(\v2\r.work.CommentR\acomment\"a\n" +
	"\x11CreateCommentResp\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12\x12\n" +
	"\x04code\x18\x7f \x01(\x05R\x04code\x12\x19\n" +
	"\amessage\x18\x80\x01 \x01(\tR\amessage\"c\n" +
	"\x16ListCommentByPostIdReq\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x120\n" +
	"\n" +
	"pagination\x18\n" +
	" \x01(\v2\x10.work.PaginationR\n" +
	"pagination\"\x90\x01\n" +
	"\x17ListCommentByPostIdResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x120\n" +
	"\fcomment_list\x18\x02 \x03(\v2\r.work.CommentR\vcommentList\x12\x12\n" +
	"\x04code\x18\x7f \x01(\x05R\x04code\x12\x19\n" +
	"\amessage\x18\x80\x01 \x01(\tR\amessage2\xa0\x04\n" +
	"\vWorkService\x121\n" +
	"\bRegister\x12\x11.work.RegisterReq\x1a\x12.work.RegisterResp\x12(\n" +
	"\x05Login\x12\x0e.work.LoginReq\x1a\x0f.work.LoginResp\x127\n" +
	"\n" +
	"CreatePost\x12\x13.work.CreatePostReq\x1a\x14.work.CreatePostResp\x127\n" +
	"\n" +
	"UpdatePost\x12\x13.work.UpdatePostReq\x1a\x14.work.UpdatePostResp\x121\n" +
	"\bListPost\x12\x11.work.ListPostReq\x1a\x12.work.ListPostResp\x12@\n" +
	"\rGetPostDetail\x12\x16.work.GetPostDetailReq\x1a\x17.work.GetPostDetailResp\x127\n" +
	"\n" +
	"DeletePost\x12\x13.work.DeletePostReq\x1a\x14.work.DeletePostResp\x12@\n" +
	"\rCreateComment\x12\x16.work.CreateCommentReq\x1a\x17.work.CreateCommentResp\x12R\n" +
	"\x13ListCommentByPostId\x12\x1c.work.ListCommentByPostIdReq\x1a\x1d.work.ListCommentByPostIdRespB\x06Z\x04./pbb\x06proto3"

var (
	file_work_proto_rawDescOnce sync.Once
	file_work_proto_rawDescData []byte
)

func file_work_proto_rawDescGZIP() []byte {
	file_work_proto_rawDescOnce.Do(func() {
		file_work_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_work_proto_rawDesc), len(file_work_proto_rawDesc)))
	})
	return file_work_proto_rawDescData
}

var file_work_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_work_proto_goTypes = []any{
	(*LoginReq)(nil),                // 0: work.LoginReq
	(*LoginResp)(nil),               // 1: work.LoginResp
	(*RegisterReq)(nil),             // 2: work.RegisterReq
	(*RegisterResp)(nil),            // 3: work.RegisterResp
	(*User)(nil),                    // 4: work.User
	(*Post)(nil),                    // 5: work.Post
	(*CreatePostReq)(nil),           // 6: work.CreatePostReq
	(*CreatePostResp)(nil),          // 7: work.CreatePostResp
	(*UpdatePostReq)(nil),           // 8: work.UpdatePostReq
	(*UpdatePostResp)(nil),          // 9: work.UpdatePostResp
	(*Pagination)(nil),              // 10: work.Pagination
	(*ListPostReq)(nil),             // 11: work.ListPostReq
	(*ListPostResp)(nil),            // 12: work.ListPostResp
	(*GetPostDetailReq)(nil),        // 13: work.GetPostDetailReq
	(*GetPostDetailResp)(nil),       // 14: work.GetPostDetailResp
	(*DeletePostReq)(nil),           // 15: work.DeletePostReq
	(*DeletePostResp)(nil),          // 16: work.DeletePostResp
	(*Comment)(nil),                 // 17: work.Comment
	(*CreateCommentReq)(nil),        // 18: work.CreateCommentReq
	(*CreateCommentResp)(nil),       // 19: work.CreateCommentResp
	(*ListCommentByPostIdReq)(nil),  // 20: work.ListCommentByPostIdReq
	(*ListCommentByPostIdResp)(nil), // 21: work.ListCommentByPostIdResp
}
var file_work_proto_depIdxs = []int32{
	4,  // 0: work.LoginResp.user:type_name -> work.User
	4,  // 1: work.RegisterResp.user:type_name -> work.User
	4,  // 2: work.Post.author:type_name -> work.User
	5,  // 3: work.CreatePostReq.post:type_name -> work.Post
	10, // 4: work.ListPostReq.pagination:type_name -> work.Pagination
	5,  // 5: work.ListPostResp.post_list:type_name -> work.Post
	5,  // 6: work.GetPostDetailResp.post:type_name -> work.Post
	4,  // 7: work.Comment.author:type_name -> work.User
	17, // 8: work.CreateCommentReq.comment:type_name -> work.Comment
	10, // 9: work.ListCommentByPostIdReq.pagination:type_name -> work.Pagination
	17, // 10: work.ListCommentByPostIdResp.comment_list:type_name -> work.Comment
	2,  // 11: work.WorkService.Register:input_type -> work.RegisterReq
	0,  // 12: work.WorkService.Login:input_type -> work.LoginReq
	6,  // 13: work.WorkService.CreatePost:input_type -> work.CreatePostReq
	8,  // 14: work.WorkService.UpdatePost:input_type -> work.UpdatePostReq
	11, // 15: work.WorkService.ListPost:input_type -> work.ListPostReq
	13, // 16: work.WorkService.GetPostDetail:input_type -> work.GetPostDetailReq
	15, // 17: work.WorkService.DeletePost:input_type -> work.DeletePostReq
	18, // 18: work.WorkService.CreateComment:input_type -> work.CreateCommentReq
	20, // 19: work.WorkService.ListCommentByPostId:input_type -> work.ListCommentByPostIdReq
	3,  // 20: work.WorkService.Register:output_type -> work.RegisterResp
	1,  // 21: work.WorkService.Login:output_type -> work.LoginResp
	7,  // 22: work.WorkService.CreatePost:output_type -> work.CreatePostResp
	9,  // 23: work.WorkService.UpdatePost:output_type -> work.UpdatePostResp
	12, // 24: work.WorkService.ListPost:output_type -> work.ListPostResp
	14, // 25: work.WorkService.GetPostDetail:output_type -> work.GetPostDetailResp
	16, // 26: work.WorkService.DeletePost:output_type -> work.DeletePostResp
	19, // 27: work.WorkService.CreateComment:output_type -> work.CreateCommentResp
	21, // 28: work.WorkService.ListCommentByPostId:output_type -> work.ListCommentByPostIdResp
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_work_proto_init() }
func file_work_proto_init() {
	if File_work_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_work_proto_rawDesc), len(file_work_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_work_proto_goTypes,
		DependencyIndexes: file_work_proto_depIdxs,
		MessageInfos:      file_work_proto_msgTypes,
	}.Build()
	File_work_proto = out.File
	file_work_proto_goTypes = nil
	file_work_proto_depIdxs = nil
}
